name: Gentsshop CI

on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - master

jobs:
  fe:
    name: Frontend CI
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request_review' && 
       github.event.review.state == 'approved' &&
       github.event.pull_request.base.ref == 'master')

    environment: dev

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Build Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t $DOCKER_USERNAME/gentsshop-frontend:latest -f Dockerfile.Frontend.v2 .
          docker tag $DOCKER_USERNAME/gentsshop-frontend:latest $DOCKER_USERNAME/gentsshop-frontend:${{ github.sha }}

      - name: Push Docker Image to Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/gentsshop-frontend:latest
          docker push $DOCKER_USERNAME/gentsshop-frontend:${{ github.sha }}

  be:
    name: Backend CI
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request_review' && 
       github.event.review.state == 'approved' &&
       github.event.pull_request.base.ref == 'master')

    environment: dev

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Build Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t $DOCKER_USERNAME/gentsshop-backend:latest -f Dockerfile.Backend .
          docker tag $DOCKER_USERNAME/gentsshop-backend:latest $DOCKER_USERNAME/gentsshop-backend:${{ github.sha }}

      - name: Push Docker Image to Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/gentsshop-backend:latest
          docker push $DOCKER_USERNAME/gentsshop-backend:${{ github.sha }}